### PR TITLE
Add SW2, SW3 and the Arduino pin names to target.json.

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**
Adapted from the K64F target.

### CODE REVIEW

**Comment by 0xc0170** [comment]
I don't see any sw2,3 buttons on this board, neither it's arduino compatible?

**Comment by markus-becker-tridonic-com** [comment]
Argh. I was trying to get the 6lowpan example to compile for an ST target.

Mixed up Discovery board and Nucleo board, latter has an Arduino header. The F429 is for us an intermediate step to the Nucleo-F401RE. Were should one define this then to make the example at least compile for an ST target?

**Comment by 0xc0170** [comment]
You should create an issue in the 6lowpan example as it's written for only K64F (not all boards have 3 buttons for instance), where we can continue how to fix it. I think there should be yotta config for this, similar for our tests, to define tests pins (hw tests which require hw like spi, etc).

I'll close this PR.

**Comment by markus-becker-tridonic-com** [comment]
OK, opened an issue against atmel-rf-driver to not hard-code the pins:
https://github.com/ARMmbed/atmel-rf-driver/issues/8

**Pull request closed without merging**
