### PR TITLE
Add target configuration in yotta.

### PR DESCRIPTION
**Pull request by niklas-arm**
First step for moving `device.h` and `target_config.h` out of the chip specific mbed-hal. See https://github.com/ARMmbed/mbed-hal/pull/63.

@0xc0170 @bremoran @autopulated @bogdanm

### CODE REVIEW

**Comment by autopulated** [comment]
:thumbsup:

`true` and `false` in config will turn into 1 and 0 also, but maybe that's less explicit.

**Comment by niklas-arm** [comment]
I actually considered merging `spi` and `spi_module_size`:

```json
"mbed-hal": {
       "spi": "6",
},
```

**Comment by autopulated** [comment]
I guess this would be the opportunity to do that if we're going to. Presumably we'd do the same for all the other modules even though they don't currently care?

**Comment by niklas-arm** [comment]
The issue is with UART:
It's not enough to know how many UARTs you have, but *which* UARTs you have.
ie. 1, 2, 3 and 6. but not 4 or 5. But you still need to reserve an array of 6, because thats the index for it.

**Comment by niklas-arm** [comment]
So the `MODULE_SIZE_*` concepts is slightly broken.
It also makes no sense to encode each UART individually, because that information is already available in the device headers.

ie. querying on `#if MODULE_UART_3_AVAILABLE` is no different than `ifdef USART3_BASE`.

**Comment by autopulated** [comment]
right, so that suggests that the number information should be separate from enable/disable – so I don't think we should combine them

**Comment by 0xc0170** [comment]
> So the MODULE_SIZE_* concepts is slightly broken.

Outside HAL - peripheral has x modules
In HAL - the module number does not need to be the peripheral module index, for instance a module number 3 is not UART3, can be low power uart 0 or uart6 (internal to HAL - mapping).

**Comment by bremoran** [comment]
bump

**Comment by autopulated** [comment]
This one's yours to merge @bremoran :)

**Comment by 0xc0170** [comment]
@niklas-arm Is this still valid ? Reopen if yes, I believe it's not

**Pull request closed without merging**
