### PR TITLE
Added config for NVIC definitions

### PR DESCRIPTION
**Pull request by AlessandroA**
This PR adds config entries for the following definitions:
```C
NVIC_NUM_VECTORS
NVIC_USER_IRQ_OFFSET
NVIC_RAM_VECTOR_ADDRESS
NVIC_FLASH_VECTOR_ADDRESS
```

when these changes are merged, the related PRs can be merged, so that `cmsis_nvic.*` files are moved from hw-specific `cmsis-core-*` modules to `cmsis-core`, to avoid duplication

### CODE REVIEW

**Comment by AlessandroA** [comment]
@bogdanm @bremoran

**Comment by AlessandroA** [comment]
@bremoran @0xc0170 I think this could be safely merged as it does not introduce any incompatibility and will help with the other (still open) PRs for cmsis

**Comment by 0xc0170** [comment]
LGTM

**Comment by bremoran** [comment]
LGTM

**Pull request merged**
